package com.example.namasayawheny.hero_ex;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;



public class DB_Hero extends SQLiteOpenHelper {
    final static String DB_NAME = "db_Hero";

    public DB_Hero(Context context) {
        super(context, DB_NAME, null, 1);
        // TODO Auto-generated constructor stub
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        String sql = "CREATE TABLE IF NOT EXISTS Hero(_id INTEGER PRIMARY KEY AUTOINCREMENT, nama TEXT, biografi TEXT, img BLOB)";
        db.execSQL(sql);

        ContentValues values = new ContentValues();
        values.put("_id", "1");
        values.put("nama", "Raden Adjeng Kartini");
        values.put("biografi", " Raden Ajeng Kartini Djojo Adhiningrat adalah nama lengkap beliau. Ia dilahirkan pada tanggal 21 April 1879 di Mayong, Jepara, Jawa Tengah. Ayahnya yang bernama Raden Mas Adipati Ario Sosroningrat merupakan seorang bupati Jepara. Kartini adalah keturunan ningrat. Hal ini bisa dilihat dari silsilah keluarganya. Kartini adalah putri dari istri pertama, tetapi bukan istri utama. Ibunya bernama M.A. Ngasirah, putri dari NyaiHaji Siti Aminah dan Kyai Haji Madirono, seorang guru agama di Telukawur, Jepara. Dari sisi ayahnya, silsilah Kartini dapat dilacak hingga Hamengkubuwana VI. Garis keturunan Bupati Sosroningrat bahkan dapat ditilik kembali ke istana Kerajaan Majapahit. Semenjak Pangeran Dangirin menjadi bupati Surabaya pada abad ke-18, nenek moyang Sosroningrat mengisi banyak posisi penting di Pangreh Praja. Ayah Kartini pada mulanya adalah seorang wedana di Mayong. Peraturan kolonial waktu itu mengharuskan seorang bupati beristerikan seorang bangsawan. Karena M.A. Ngasirah bukanlah bangsawan tinggi, maka ayahnya menikah lagi dengan Raden Adjeng Woerjan (Moerjam), keturunan langsung Raja Madura. Setelah perkawinan itu, maka ayah Kartini diangkat menjadi bupati di Jepara menggantikan kedudukan ayah kandung R.A. Woerjan, R.A.A. Tjitrowikromo.\n" +
                "\n" +
                "Kartini adalah anak ke-5 dari 11 bersaudara kandung dan tiri. Dari kesemua saudara sekandung, Kartini adalah anak perempuan tertua. Kakeknya, Pangeran Ario Tjondronegoro IV, diangkat bupati dalam usia 25 tahun dan dikenal pada pertengahan abad ke-19 sebagai salah satu bupati pertama yang memberi pendidikan Barat kepada anak-anaknya. Kakak Kartini, Sosrokartono, adalah seorang yang pintar dalam bidang bahasa. Sampai usia 12 tahun, Kartini diperbolehkan bersekolah di ELS (Europese Lagere School). Di sini antara lain Kartini belajar bahasa Belanda. Tetapi setelah usia 12 tahun, ia harus tinggal di rumah karena sudah bisa dipingit. Beliau bersekolah hanya sampai sekolah dasar. Ia berkeinginan untuk melanjutkan sekolahnya, tapi tidak diizinkan oleh orangtuanya. Sebagai seorang gadis, Kartini harus menjalani masa pingitan hingga sampai waktunya untuk menikah. Ini merupakan suatu adat yang harus dijalankan pada waktu itu. Kartini hanya dapat memendam keinginannnya untuk bersekolah tinggi.\n" +
                "\n" +
                "Untunglah beliau gemar membaca dari buku – buku, koran, sampai majalah Eropa. Kartini tertarik pada kemajuan berpikir perempuan Eropa .Kartini banyak membaca surat kabar Semarang De Locomotief yang diasuh Pieter Brooshooft, ia juga menerima leestrommel (paket majalah yang diedarkan toko buku kepada langganan). Di antaranya terdapat majalah kebudayaan dan ilmu pengetahuan yang cukup berat, juga ada majalah wanita Belanda De Hollandsche Lelie. Di antara buku yang dibaca Kartini sebelum berumur 20, terdapat judulMax Havelaar dan Surat-Surat Cinta karya Multatuli, yang pada November 1901 sudah dibacanya dua kali. Lalu De Stille Kraacht (Kekuatan Gaib) karya Louis Coperus. Kemudian karya Van Eeden yang bermutu tinggi, karya Augusta de Witt yang sedang-sedang saja, roman-feminis karya Nyonya Goekoop de-Jong Van Beek dan sebuah roman anti-perang karangan Berta Von Suttner, Die Waffen Nieder(Letakkan Senjata). Semuanya berbahasa Belanda. Pikirannya menjadi terbuka lebar, apalagi setelah membandingkan keadaan wanita di Eropa dengan wanita Indonesia. Sejak itu, timbullah keinginan beliau untuk memajukan perempuan pribumi yang pada saat itu berada pada status sosial yang rendah. Ia ingin memajukan wanita Indonesia melalui pendidikan. Untuk itu, beliau mendirikan sekolah bagi gadis – gadis di Jepara, karena pada saat itu ia berdomisili di Jepara. Muridnya hanya berjumlah 9 orang yang terdiri dari kerabat atau famili.\n" +
                "\n" +
                "Di samping itu, ia banyak pula menulis surat untuk teman-temannya orang Belanda.  Salah satunya adalah Rosa Abendanon yang banyak mendukungnya. Dalam surat itulah ia melampiaskan cita-citanya untuk menuntut persamaan hak dan kewajiban antara pria dan wanita. Kartini pun kemudian beberapa kali mengirimkan tulisannya dan akhirnya dimuat diDe Hollandsche Lelie, sebuah majalah terbitan Belanda yang selalu ia baca. Dari surat-suratnya, tampak Kartini membaca apa saja dengan penuh perhatian, sambil membuat catatan-catatan. Kadang-kadang Kartini menyebut salah satu karangan atau mengutip beberapa kalimat. Perhatiannya tidak hanya semata-mata soalemansipasi wanita, tapi juga masalah sosial umum. Kartini melihat perjuangan wanita agar memperoleh kebebasan, otonomi dan persamaan hukum sebagai bagian dari gerakan yang lebih luas.\n" +
                "\n" +
                "Beliau sempat mendapatkan beasiswa dari Pemerintah Belanda karena tulisan-tulisan hebatnya, namun ayahnya pada saat itu memutuskan agar Kartini harus menikah dengan R.M.A.A. Singgih Djojo Adhiningrat, Bupati Rembang kala ituyang sudah pernah memiliki tiga istri. Kartini menikah pada tanggal 12 November 1903. Sejak itu, Kartini harus hijrah dari Jepara ke Rembang mengikuti suaminya.  Suaminya mengerti keinginan Kartini dan Kartini diberi kebebasan dan didukung mendirikan sekolah wanita di sebelah timur pintu gerbang kompleks kantor kabupaten Rembang, atau di sebuah bangunan yang kini digunakan sebagai Gedung Pramuka.\n" +
                "\n" +
                "Kartini memiliki seorang anak lelaki bernama Soesalit Djojoadhiningrat, yang dilahirkan pada tanggal 13 September 1904. Selang beberapa hari pasca melahirkan, Kartini tutup usia pada tanggal 17 September 1904. Kartini meninggal pada usia 25 tahun. Beliau dimakamkan di Desa Bulu, Kecamatan Bulu, Rembang.\n" +
                "\n" +
                "Untuk menghormati kegigihan beliau, didirikanlahSekolah Wanita oleh Yayasan Kartini di Semarang pada tahun1912, kemudian di Surabaya, Yogyakarta, Malang, Madiun, Cirebon dan daerah lainnya. Nama sekolah tersebut adalah \"Sekolah Kartini\". Yayasan Kartini ini didirikan oleh keluarga Van Deventer, seorang tokoh Politik Etis.Setelah Kartini wafat, Mr.J.H. Abendanon mengumpulkan dan membukukan surat-surat yang pernah dikirimkan R.A Kartini pada teman-temannya di Eropa. Abendanon saat itu menjabat sebagai Menteri Kebudayaan, Agama, dan Kerajinan Hindia Belanda. Buku itu diberi judul Door Duisternis tot Licht yang arti harfiahnya \"Dari Kegelapan Menuju Cahaya\". Buku kumpulan surat Kartini ini diterbitkan pada 1911. Buku ini dicetak sebanyak lima kali, dan pada cetakan terakhir terdapat tambahan surat Kartini.\n" +
                "\n" +
                "Pada tahun 1922, Balai Pustaka menerbitkannya dalam bahasa Melayu dengan judul yang diterjemahkan menjadi Habis Gelap Terbitlah Terang: Boeah Pikiran, yang merupakan terjemahan oleh Empat Saudara. Kemudian tahun 1938, keluarlah Habis Gelap Terbitlah Terang versi Armijn Pane seorang sastrawan Pujangga Baru. Armijn membagi buku menjadi lima bab pembahasan untuk menunjukkan perubahan cara berpikir Kartini sepanjang waktu korespondensinya. Versi ini sempat dicetak sebanyak sebelas kali. Surat-surat Kartini dalam bahasa Inggris juga pernah diterjemahkan oleh Agnes L. Symmers. Selain itu, surat-surat Kartini juga pernah diterjemahkan ke dalam bahasa-bahasa Jawa dan Sunda.\n" +
                "\n" +
                "Terbitnya surat-surat Kartini, seorang perempuan pribumi, sangat menarik perhatian masyarakat Belanda, dan pemikiran-pemikiran Kartini mulai mengubah pandangan masyarakat Belanda terhadap perempuan pribumi di Jawa. Pemikiran-pemikiran Kartini yang tertuang dalam surat-suratnya juga menjadi inspirasi bagi tokoh-tokoh kebangkitan nasional Indonesia, antara lain W.R. Soepratman yang menciptakan lagu berjudul Ibu Kita Kartini.\n" +
                "\n" +
                "Sayangnya, banyak kontroversi bermunculan dikarenakan ketetapan Ir. Soekarno, Presiden pertama Republik Indonesia,melalui Keputusan Presiden Republik Indonesia No.108 Tahun 1964, tanggal 2 Mei 1964, yang menetapkan Kartini sebagai Pahlawan Kemerdekaan Nasional sekaligus menetapkan hari lahir Kartini, tanggal 21 April, untuk diperingati setiap tahun sebagai hari besar yang kemudian dikenal sebagai Hari Kartini.Bahkan lagu Ibu Kita Kartini yang diciptakan oleh W.R. Supratman menjadi salah satu lagu nasional. Hal ini menuai protes dari beberapa kalangan di Indonesia. Pengistimewaan Kartini terkesan pilih kasih dari Pahlawan wanita Indonesia lainnya di berbagai belahan nusantara seperti Cut Nyak Dien, Dewi Sartika, Maria Tiahahu, Rohana Kudus, yang beberapa diantara mereka menurut para pengecam, telah ikut berperang langsung dengan para penjajah Belanda, dibandingkan Kartini yang hanya menulis. Namun, apa yang dikatakan Oov Auliansyah pada halaman (http://sosok.kompasiana.com/2013/04/21/kartinitak-layak-jadi-pahlawan-nasional-553170.html) ada benarnya, ia mengatakan bahwa, “...Kartini telah berfikir tentang perssamaan gender di awal 1900. Berbicara tentang wanita yg berhak mendapat pendidikan selayaknya kaum laki-laki (laki-laki bangsawan & Belanda, SAAT itu diskriminasi cukup kuat).\n" +
                "\n" +
                "Kartini melawan diskriminasi Belanda terhadap pribumi dan kesewenang-wenangan Belanda lewat suratnya kepada sahabat-sahabatnya di Belanda, akhirnya mampu menggugah hati pemerintah Belanda dan membangun pendidikan di Jawa. Kartini adalah anak kaum bangsawan, bisa dibilang seorang borjuis kecil, tapi kemudian dia memilih sendiri turun menjadi proletar.\n" +
                "\n" +
                "Surat-surat Kartini, seorang perempuan pribumi, sangat menarik perhatian masyarakat Belanda, dan pemikiran-pemikiran Kartini mulai mengubah pandangan masyarakat Belanda terhadap perempuan pribumi di Jawa, sehingga menimbulkan simpati dari masyarakat Belanda dan menentang kebijakan-kebijakan parlemen Belanda yg merugikan kaum pribumi Jawa...Kartini telah memikirkan tentang pendidikan kaum wanita di masyarakat Jawa pada waktu itu yg terpaku dengan segala adat-adatnya yang kaku, seolah wanita sudah tidak perlu pendidikan, bisa bahasa Belanda saja sudah cukup, kemudian tinggal menunggu dinikahi dan kemudian dimadu.Kartini telah memikirkan ini di awal 1900-an.\n");
        values.put("img", R.drawable.kartini);
        db.insert("Hero", "_id", values);

        values.put("_id", "2");
        values.put("nama", "Pangeran Diponegoro");
        values.put("biografi", "Pangeran Diponegoro adalah tokoh sentral di dalam Perang Diponegoro. Lalu, seperti apa sosok tokoh Pahlawan Nasional yang satu ini? Kita akan membahasnya untuk anda. Diponegoro lahir pada 11 November 1785 di Jogja. Setelah melakukan perjuangan sekian lama, ia menghembuskan nafas terakhirnya pada 8 Januari 1855 di Sulawesi. Saat itu ia sudah menginjak usia 69 tahun. Diponegoro adalah putra dari tokoh yang disegani bernama Hamengkubuwana III.\n" +
                "\n" +
                "Ia adalah seorang raja dari Mataram. Sang ibu bernama R.A. Mangkarawati, ia berdarah Pacitan. Saat dilahirkan, Diponegoro memiliki nama Bendoro Raden Mas Ontowiryo. Sang Ayah sempat punya niat untuk mengangkatnya sebagai raja. Hanya saja waktu itu ia sadar bahwa ia hanya putra dari seorang selir, sehingga menolak keinginan dari ayahnya tersebut. Sepanjang hidupnya, Diponegoro pernah mempersuntingnya banyak istri, diantaranya adalah Raden Ayu Ratnaningrum, Bendara Raden Ayu Antawirya, dan Raden Ayu Ratnaningsih.\n" +
                "\n" +
                "Kehidupannya lebih banyak dihabiskan untuk mendalami agama. Ia juga dikenal sangat merakyat dan banyak tinggal di Tegalrejo. Ada satu momen dimana ia melakukan pemberontakan terhadap keraton dan ini bermula saat keraton berada di bawah pemerintahan Hamengkubuwana V (1822). Ia saat itu bertindak sebagai anggota perwalian. Ia tidak menyukai prosedur perwalian tersebut. Diponegoro adalah sosok pejuang luar biasa. Ia tidak suka dengan Belanda sejak mereka berani memasang patok di tanah miliknya yang berlokasi di Tegalrejo. Itu tidak lain adalah karena Belanda dinilai semena-mena terhadap masyarakat.\n" +
                "\n" +
                "Mereka juga suka membebani pajak kepada rakyat. Ia pun menunjukkan ketidaksukaannya secara terbuka dan sikap ini ternyata banyak mendapat dukungan dari masyarakat. Sang paman Pangeran Mangkubumi kemudian memintanya pindah dari Tegalrejo untuk memikirkan strategi melawan kaum kafir. Ia menamai perjuangan tersebut sebagai Perang Sabil. Semangat tersebut tidak hanya menyulut semangat orang-orang terdekatnya saja, namun mleluas hingga ke Kedu dan Pacitan. Bahkan tokoh agama penting seperti Kyai Maja juga turut serta di dalam perjuangan tersebut.\n" +
                "\n" +
                "Perang tersebut menyebabkan kerugian di pihak kolonial. Mereka kehilangan banyak prajurit, bahkan mencapai 15.000 orang. Karena dinilai membahayakan, mereka pun membuat sayembara dengan hadiah 50.000 Gulden supaya orang tertarik ikut serta dalam perburuan tersebut. Diponegoro baru berhasil ditangkap di tahun 1830.\n" +
                "\n" +
                "Beberapa minggu setelah ditangkap, 28 Maret 1830, ia bertemu dengan Jenderal de Kock di Magelang. Sang jenderal meminta supaya Diponegoro tidak melakukan aksi serangan lagi. Ia pun menolaknya, sehingga berdampak pada pengasingan dirinya ke Ungaran, kemudian Semarang, dan terakhir Batavia. Tidak berhenti disini, ia kembali dipindahkan beberapa kali dari satu tempat ke tempat lainnya, bahkan sampai ke Manado.");
        values.put("img", R.drawable.diponegoro);
        db.insert("Hero", "_id", values);


        values.put("_id", "3");
        values.put("nama", "Ir. Soekarno");
        values.put("biografi", "Siapa yang tidak kenal dengan Ir. Soekarno. Semua orang di Indonesia pasti kenal dengan beliau. Beliau adalah Presiden pertama Republik Indonesia. Sebagai rakyat Indonesia dan mencintai sejarah, anda harus mengetahui biografi Ir.Soekarno. beliau merupakan sosok yang banyak dikagumi oleh semua orang. Berkat perjuangan beliau, Indonesia bisa merdeka dari tangan para penjajah. Bapak ir. Soekarno lebih dikenal dengan nama bung karno. Beliau lahir di Blitar pada tanggal 6 juni 1901. Nama asli dari Bung karno adalah Koesno Sosrodiharjo. Mari kita bahas lebih lanjut tentang perjalanan hidup bung karno.\n" +
                "\n" +
                "Nama Soekarno diberi ketika soekarno sering mengalami sakit ketika memiliki nama Koesno Sosrodiharjo. Menurut orang zaman dulu, orang tersebut keberatan nama sehingga sering sakit. Dari beberapa buku biografi Ir soekarno menyebutkan bahwa nama dari bapak Ir soekarno adalah Raden Soekemi Sosrodihardjon dan beliau mempunyai ibu yang bernama Ida Ayu Nyoman Rai. Bung karno meninggal dunia pada umur 69 tahun yaitu pada tanggal 21 juni 1970 di Jakarta. Banyak sekali sejarah yang menceritakan tentang masa-masa kejayaan beliau. Ketika masih kecil beliau tinggal bersama kakeknya di daerah Tulungagung, jawa timur.\n" +
                "\n" +
                "Pada saat beliau berumur 14 tahun beliau diajak untuk tinggal di Surabaya dan bersekolah di Hoogere Burger School (H.B.S) oleh teman ayahnya yang bernama Oemar Said Tjokroaminoto. Dari buku biografi Ir. Soekarno diceritakan bahwa beliau mulai kenal dengan pemimpin serikat islam pada saat beliau tinggal di Surabaya. Pada saat itu serikat islam di pimpin oleh Bapak Tjokroaminoto. Pada saat itu juga soekarno mulai gabung dengan organisasi Pemuda java atau Jong Java. Bung karno tamat dari sekolah hoogere burger School pada tahun 1920. Setelah itu beliau melanjutkan sekolah di ITB yang dulu bernama Technische Hoge School dan lulus pada tahun 1925.\n" +
                "\n" +
                "Jika melihat dari biografi Ir. Soekarno beliau banyak mendirikan dan bergabung dengan berbagai organisasi. Pada saat tinggal di bandung, beliau pernah mendirikan organisasi Algemene Studi Club pada tahun 1926. Pada tahun 1927 Ir soekarno merubah organisasi ini menjadi Partai Nasional Indonesia. Ketika mendirikan Partai Nasional Indonesia inilah, bung karno ditangkap oleh Belanda pada bulan desember 1929 dan beliau dibebaskan pada bulan desember tahun 1931. Hal itu juga dikarenakan Pledoi Indonesia menggugat yang sangat terkenal pada waktu itu.\n" +
                "\n" +
                "Ir soekarno mempunyai 3 istri, istri pertama bernama Fatmawati dan mempunyai anak yang bernama rachmawati, megawati, Guntur dan juga guruh. Dari istri keduanya yang bernama hartini beliau mempunyai dua anak yang bernama bayu dan taufan. Istri ketiga beliau merupakan seorang wanita yang mempunyai kebangsaan Jepang yang bernama naoko nemoto dan berganti nama bernama ratna sari dewi dan dikarunia anak bernama kartika. Ketika berbicara tentang biografi Ir. Soekarno memang tidak ada habisnya. Ada banyak sekali sejarah tentang perjalanan hidup presiden pertama Indonesia ini. .");
        values.put("img", R.drawable.sukarno);
        db.insert("Hero", "_id", values);

        values.put("_id", "4");
        values.put("nama", "Tuanku Imam Bonjol");
        values.put("biografi", "Ada banyak sekali pahlawan Indonesia yang harus kita kenang sejarahnya dan selalu kita banggakan. Bangsa yang hebat adalah bangsa yang menghargai sejarahnya. Salah satu pahlawan yang sangat berjasa untuk Indonesia adalah Tuanku Imam Bonjol. Nama asli dari tuanku imam bonjol adalah Muhammad sahib atau Petto syarif. Ayah beliau merupakan seorang guru agama yang bernama Buya nurdin. Ilmu agama yang beliau dapat juga dari ayahannya. Tuanku imam bonjol merupakan seorang guru agama di daerah bonjol. Oleh karena itu namanya berubah menjadi tuanku imam bonjol. Biografi tuanku imam bonjol, akan lebih dijelaskan lebih jauh lagi diartikel dibawah ini.\n" +
                "\n" +
                "Pada tahun 1821 terjadi perang padrie yang di pimpin oleh tuanku imam bonjol. Perang ini merupakan perang antara kaum padre yang ingin belajar agama dengan baik dan benar melawan kaum adat yang dimotori oleh pemerintahan Belanda. Dengan perlawanan yang keras dari kaum padre membuat seluruh pasukan Belanda menjadi menyerah. Pada tahun 1824 pemerintahan Belanda mengadakan perjanjian damai yang lebih dikenal dengan perjanjian masang. Tetapi tidak membutuhkan waktu yang lama, perjanjian damai tersebut juga dilanggar sendiri oleh pemerintahan Belanda. Cerita tentang pernah padrie dan perjanjian masang banyak diceritakan di berbagai buku biografi Tuanku imam bonjol.\n" +
                "\n" +
                "Pada saat Belanda melanggar perjanjian tersebut, rakyat padrie dan juga dari kaum adat akhirnya sadar kalau semua hal tersebut hanya akan merugikan rakyat Sumatra barat dan membuat Belanda dapat masuk ke daerah minangkabau. Akhirnya warga padrie dan kaum adat juga melakukan perjanjian damai sendiri yang ditulis di plakat tabek patah. Pada tahun 1833 akhirnya seluruh rakyat miangkabau sumatera barat bersatu untuk mengusir Belanda dari tanah mereka. Akhirnya Belanda selama 3 tahun menyerah dna tidak dapat menguasai daerah bonjol yang merupakan daerah incaran mereka. Jika membaca buku biografi tuanku imam bonjol, anda akan tahu bagaimana perjuangan tuanku imam bonjol melawan penjajah Belanda.\n" +
                "\n" +
                "Selanjutnya Belanda mengeluarkan pasukan lebih banyak yang lebih dikenal dengan pasukan sepoys. Hampir 6000 pasukan Belanda mengepung seluruh daerah di bonjol. Akhirnya daerah bonjol baru dapat direbut oleh Belanda pada 16 agustus tahun 1837. Tunaku imam bonjol dibuang oleh Belanda ke daerah cianjur, kemudian pindah ke ambon dan akhirnya beliau pindah ke lontan daerah manado. Beliau wafat pada tanggal 6 november tahun 1864 di pembuangan terakhirnya yaitu di manado. Melihat semua perjuangan beliau di buku biografi tuanku imam bonjol, memang sangat besar rasa cinta beliau terhadap Indonesia.\n" +
                "\n" +
                "Rasa juang dan patriotisme yang sangat tinggi harus selalu kita junjung dari beliau. Beliau adalah seorang pemimpin yang sangat baik, selain itu beliaulah yang mengajarkan tentang agama islam di seluruh tanah minangkabau. Beliau tidak hanya mementingkan kehidupannya sendiri. beliau juga memperjuangkan semua kepentingan rakyat dan benar-benar berjuang untuk mengusir Belanda dari sumatera barat. .");
        values.put("img", R.drawable.imambonjol);
        db.insert("Hero", "_id", values);

        values.put("_id", "5");
        values.put("nama", "Dr. Drs. H. Mohammad Hatta");
        values.put("biografi", "Siapa yang tidak kenal dengan Bung hatta. Beliau adalah wakil presiden pertama republik Indonesia. Bung hatta atau Mohammad hatta lahir di bukit tinggi pada tanggal 12 Agustus 1902. Beliau mulai kenal dengan berbagai pergerakan sejak tinggal di MULO kota padang. Selain itu beliau juga masuk di organisasi Jong Sumatranen Bond. Beliau juga pernah menempuh sekolah di Belanda yaitu di sekolah Handels Hoge School Roterdam pada tahun 1921. Dalam beberapa buku biografi Mohammad Hatta, beliau juga pernah ikut bergabung dalam organisasi pergerakan yaitu Indische Vereniging. Organisasi tersebut merupakan organisasi yang menolak kerjasama dengan Belanda.\n" +
                "\n" +
                "Mohammad Hatta lulus dari handles economis atau bisa disebut dengan ekonomi perdagangan pada tahun 1923. Awalnya beliau akan menempuh pendidikan doctor di bidang ekonomi tetapi pada tahun tersebut juga dibuka jurusan baru yaitu hukum Negara dan hukum administrasi. Akhirnya beliau lebih memilih untuk melanjutkan ke jurusan tersebut dibandingkan ke jurusan doctoral. Karena masalah perpajangan studinya ini, beliau akhirnya menjadi ketua PI (perhimpunan Indonesia). Beliau juga pernah menyampaikan pidato tentang struktur ekonomi dunia dan juga tentang pertentangan kekuasaan. Pidato ini banyak sekali diceritakan di berbagai buku biografi Mohammad Hatta.\n" +
                "\n" +
                "Dari tahun 1926 sampai tahun 1930, Mohammad hatta selalu menjadi ketua di perhimpunan Indonesia. Sampai beberapa waktu akhirnya Perhimpunan Indonesia berbuah menjadi sebuah organisasi politik. PI awalnya Cuma perhimpunan mahasiswa Indonesia. Perhimpunan Indonesia dapat mempengaruhi pergerakan politik di Indonesia pada waktu itu. Sampai akhirnya pemufakatan perhimpunan politik Indonesia mengakui PI sebagai salah satu gerakan pergerakan politik Indonesia yang berasal dari Eropa. Dalam buku Biografi Mohammad hatta diceritakan bahwa Pi melakukan berbagai propaganda di luar Belanda. Setiap melakukan perkumpulan di eropa, selalu Mohammad hatta sendiri yang menjadi delegasi dari PI.\n" +
                "Pada tahun 1923, Mohammad hatta pulang ke tanah air Indonesia. Pada saat di Indonesia beliau lebih banyak disibukkan dengan menulis artikel politik yang di muat di surat kabar daulat ra'jat. Selain itu beliau juga mengadakan berbagai kegiatan politik dan juga melatih kader-kader politik dari partai Pendidikan nasional Indonesia. Pada saat penahan Soekarono di ende flores, Mohammad hatta banyak menuliskan artikel pertentangan keras terhadap penahannya tersebut. Pada bulan februari, pemeritahan Belanda akhirnya menahan semua pemimpin dari partai pendidikan nasional Indonesia. Ada 7 orang anggota partai yang ditahan di daerah Boven Digoel. Pada biografi Mohammad Hatta, dituliskan ketika beliau dipenjara beliau sempat menulis buku yang berjudul krisis ekonomi dan kapitalisme.\n" +
                "\n" +
                "Beliau dan teman-temannya mengalami pembuangan ke berbagai hal. Tetapi selama mengalami masa tersebut Mohammad Hatta tetap menulis berbagai artikel tentang politik dan juga ekonomi. Pada masa pemerintahan Jepang, Mohammad Hatta sempat ditawarin untuk menjadi penasehat pemerintahan Belanda. Pada masa pambacaan teks proklamasi, beliau diminta oleh Soekarno untuk menyusun teks proklamasi.");
        values.put("img", R.drawable.hatta);
        db.insert("Hero", "_id", values);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS Hero");
        onCreate(db);

    }

}